### PR TITLE
Implement initpin function #128

### PR DESCRIPTION
**Pull request by KingAnointing**

### CODE REVIEW

**Comment by JeremyRand** [comment]
Some of the compile fails look like an infrastructure issue, I've triggered a rebuild.

**Comment by JeremyRand** [comment]
Please split off the `.gitignore` fix into a separate PR so that it can be reviewed independently.

**Comment by JeremyRand** [comment]
Please fix the `gofumpt` warning; let me know on Matrix if you're having trouble with that.

**Comment by JeremyRand** [comment]
Seems another Cirrus rebuild is needed, just triggered one.

**Comment by JeremyRand** [comment]
`gofumpt` still failing.

**Comment by KingAnointing** [comment]
Do I need to do anything or wait for cirrus to do his thing ?

**Comment by JeremyRand** [comment]
Cirrus appears to have finished the rerun, `gofumpt` fix still needed.

**Pull request closed without merging**
