### PR TITLE
Add header for C-code

### LINKED ISSUE #95: Run csbuild on C code embedded in Go code
There's [some C code embedded in Go code](https://github.com/namecoin/pkcs11mod/blob/b71ecf8f436425ee27d93dc7c664702431caf8e4/types.go#L20-L50) here; it looks like csbuild skips this because the resulting GCC calls are for files in a temporary directory instead of this repo's directory.  We should find a way to get csbuild to lint this.

### PR DESCRIPTION
**Pull request by robertmin1**
Fix #95
Add header for C-code

### CODE REVIEW

**Comment by JeremyRand** [comment]
Is this a fix for https://github.com/namecoin/pkcs11mod/issues/95 ?

**Comment by robertmin1** [comment]
Yes, ammended my commit for better clarity

**Comment by JeremyRand** [comment]
Can we name the new file `types.h`?  `main.h` may be misinterpreted as indicating something to do with the `main` package/function.

**Comment by robertmin1** [comment]
Yes, that will definitely be better and will avoid confusion.

**Comment by JeremyRand** [comment]
ACK 0a18764a8bebb363abdddbb9d2ca516b2e68309e

**Pull request merged**
