### PR TITLE
Adding go.mod and go.sum to .gitignore

### PR DESCRIPTION
**Pull request by robertmin1**
Adding go.mod and go.sum to .gitignore

### CODE REVIEW

**Comment by JeremyRand** [comment]
Can you add a newline at the end of the file?

**Comment by robertmin1** [comment]
Squashed the commits

**Comment by JeremyRand** [comment]
Tentative ACK 7f28016ff592b1d21256be89d39637783af43f1f,  lemme check into why Cirrus is failing before I merge this.

**Comment by JeremyRand** [comment]
The Cirrus fails look spurious to me, I just triggered a  rebuild, hopefully that'll resolve it.

**Comment by robertmin1** [comment]
Okay!

**Comment by JeremyRand** [comment]
Still seeing spurious Cirrus fails.  Should be fixed by https://github.com/namecoin/pkcs11mod/pull/135 but that won't help your PR unless you rebase, which is probably unnecessary here; I''ll just restart the failed builds a few times until they pass.

**Comment by JeremyRand** [comment]
ACK 7f28016ff592b1d21256be89d39637783af43f1f , merging.

**Comment by robertmin1** [comment]
Great!

**Pull request merged**
