### PR TITLE
Implementing missing p11mod CopyFunction

### PR DESCRIPTION
**Pull request by robertmin1**
Implementing a Copy Function. Made some changes to errors I had not noticed. (return error in ln 421-424)
Got a low-hanging fruit :)

### CODE REVIEW

**Comment by JeremyRand** [comment]
Can you remove the go.mod and go.sum files from your commit?  We generate those at build time rather than putting them in the Git repo; I think that's what's causing the Cirrus failures.

Also please put `Refs https://github.com/namecoin/pkcs11mod/issues/128` in your commit message so that someone looking through the Git history later will be able to find background info.

**Comment by JeremyRand** [comment]
It occurs to me that maybe we should exclude `go.mod` and  `go.sum` from Git inclusion via `.gitignore`?  I'm guessing that would have avoided the mistake of including them in the commit?

**Comment by JeremyRand** [comment]
Can you submit the `.gitignore` change as a separate PR?  I prefer to avoid mixing multiple kinds of changes into one PR.

**Comment by robertmin1** [comment]
Okay, I'll get on that

**Pull request closed without merging**
